nav:
  - name: <span class="important">Registration</span>
    url: /registration
  - name: Rules
    url: /rules
  - name: Judges
    url: /judges
  - name: Sponsors
    url: /sponsors
  - name: Prizes
    url: /prizes
  - name: Contact
    url: /#contact

# platinum_sponsor:
#   name: PegB
#   image: pegb.svg
#   logo: pegb_logo.svg
#   url: https://www.pegb.tech/
#   description: Secure Cashless Payments for everyone, everywhere
#   background_color: "#f05323"

gold_sponsors:
  - name: Erlang Solutions
    image: esl.svg
    logo: esl.png
    url: https://www.erlang-solutions.com/
    description: "Erlang, Elixir & BEAM Technology Consultancy"
    background_color: "#ab191e"

prizes:
  - name: <strong>900USD</strong> Free 2-day CodeBEAM SF ticket
    sponsor: Erlang Solutions
    sponsor_url: https://www.erlang-solutions.com/
    url: http://www.erlang-factory.com/codebeamsf2018/
    image: codebeamsf2018.jpg
  - name: <strong>4x</strong> <strong>150USD</strong> Free tickets to Any CodeBEAM Lite
    sponsor: Erlang Solutions
    sponsor_url: https://www.erlang-solutions.com/
    url: http://www.erlang-factory.com
    image: codebeamlite2018.jpg

judges:
  - name: René Föhring
    url: http://trivelop.de/
    twitter: rrrene
    image: rrrene.png
  - name: Kenji Rikitake
    url: https://rikitake.jp/
    twitter: jj1bdx
    image: kenji.jpg
  - name: Tristan Sloughter
    url: http://blog.erlware.org
    twitter: t_sloughter
    image: tristan.jpg
  - name: Miriam Pena
    url: https://www.linkedin.com/in/miriampena/
    twitter: miriampena
    image: miriam.jpg
  - name: Andrea Leopardi
    url: https://andrealeopardi.com/
    twitter: whatyouhide
    image: andrea.jpg

winner:
  # team: SampleTeam
  # project: SampleProject
  # repo: sample_repo_name
  # description: Sample Description
  # link: https://www.sample.link.org/
  # members:
  #   - name: Sample Name
  #     user: sample_user
  #     avatar: https://avatars0.githubusercontent.com/u/477062
  # prizes:
  #   - name: <strong>###USD</strong> Sample Price
  #     sponsor: Sample Sponsor
  #     sponsor_url: https://www.sample.sponsor.url.com/
  #     url: http://sample.prize.url
  #     image: sample_image.jpg
  # comments:
  #   - text: Sample comment
  #     author: Sample Author

category_winners:
  # - team: SampleTeam
  #   project: SampleProject
  #   repo: sample_repo_name
  #   description: Sample Description
  #   link: https://www.sample.link.org/
  #   category: SampleCategory
  #   members:
  #     - name: Sample Name
  #       user: sample_user
  #       avatar: https://avatars0.githubusercontent.com/u/477062
  #   prize:
  #     name: <strong>###USD</strong> Sample Price
  #     sponsor: Sample Sponsor
  #     sponsor_url: https://www.sample.sponsor.url.com/
  #     url: http://sample.prize.url
  #     image: sample_image.jpg
  #   comments:
  #     - text: Sample comment
  #       author: Sample Author

rules:
  - text: "Schedule"
    details:
      - text: The event will start on <strong>2018-11-24 00:00 UTC</strong>.
      - text: The event will end on <strong>2018-11-25 23:59 UTC</strong>.
      - text: The registration will close 2 days prior to the start date.
      - text: Each team will have exactly 48 hours to work on their projects.
  - text: Teams
    details:
      - text: "Team size is 1 to 4."
      - text: "Every team member has to be a human being, not an organization."
      - text: "All members of the team should be 13 years old or older."
      - text: "Judges of this contest can not participate in it as members of a team."
      - text: Every team has to be registered by completing the <a target="_blank" href="https://goo.gl/forms/sFt34VNjWaMzGD0r2">registration form</a>.
  - text: Projects
    details:
      - text: "All projects should be written to run on the Erlang VM / BEAM."
      - text: "They can be written in any BEAM-based language (i.e. Erlang, Elixir, LFE, efene, clojerl, etc.)."
      - text: "Supplementary languages such as Javascript (and JS frameworks) are allowed."
      - text: "No code can be created before the start of the contest."
      - text: Each team should come up with their own project idea (If you need inspiration check <a target="_blank" href="https://appideagenerator.com/">this website</a>)
      - text: "The organizing team will create a git repository at GitHub for each team."
      - text: "If a team needs more than one, they can ask the organizers to create extra repos for them."
      - text: "All deliverables should be uploaded to the repository, which is what will be used by the jury to evaluate the projects."
      - text: "The only required deliverable is the code, but everything in the repository will be used for evaluation."
      - text: "Suggested extra deliverables to include: Documentation, comprehensive README.md, project-related art (e.g. Logos), tests and anything that makes building and understanding the system easier for the judges."
      - text: "Usage of third party libraries and web services is not prohibited, even encouraged."
      - text: "<em>Ownership and Copyright:</em> Each team retains all the rights to their submissions."
      - text: "<em>User Privacy:</em> If a project is an online application (such as a web application) that collects personal information from its users, it should not reveal any of personally identifiable information unless required to do so by law. Please respect people&#8217;s privacy."
      - text: "Lawful submissions only: please do not submit anything that can be considered harmful, unlawful or both."
  - text: Evaluation
    details:
      - text: "Your work will be judged by a publicly known jury, unless previously disqualified."
      - text: "Each sponsor is responsible for delivering the prize they provided to the corresponding winning team."
      - text: "Each project will be evaluated in 6 different categories: Creativity, Usefulness, Innovation, Correctness, Maintainability and Completion."
      - text: "Final interpretation of each category meaning is up to the judges, but as general guidelines:
              <dl>
                <dt>Creativity</dt><dd>This category assigns points for unexpectedness, eccentricity, fun. This is a broad category that may apply to the project, its code, the team, etc.</dd>
                <dt>Usefulness</dt><dd>How useful the project will be for its target users. Does it solve an existing problem? Does it significantly reduce work time for its users?</dd>
                <dt>Innovation</dt><dd>How groundbreaking the project is. The more unique and unprecedented the idea behind the project, the better. Also applies to projects developed in a unique way.</dd>
                <dt>Correctness</dt><dd>The less bugs, the better. This category values working products over complete ones.</dd>
                <dt>Maintainability</dt><dd>How easy will be for future developers to keep contributing to this project after SpawnFest is over.</dd>
                <dt>Completion</dt><dd>Is the project functional? Did the team get to a point where there is something to show, even if there are a few bugs here and there?</dd>
              </dl>
              "
      - text: "Final score of each team will be computed as the sum of the points received in all those categories."
      - text: "The team with the highest final score will be the winner of the contest."
      - text: "Other prizes, besides the one for the winner, will be awarded as well."
  - text: Other Rules
    details:
      - text: "Individual participants or even entire teams can be disqualified if they don't abide by these rules. The organizers reserve the right to apply the punishment they consider fit to any transgression."
      - text: "Event organizers will not reimburse you for any expenses or losses."
      - text: "Event organizers are not responsible for any damage, legal actions or any other outcomes that might be a result of your participation."
      - text: "Event organizers reserve the right to change these rules without prior notification."
