safe: true
lsi: false
pygments: true

description: "An annual 48 hour development competition in which teams of skilled application developers get exactly one weekend to develop the best Erlang software that they can"

nav:
    - name: Home
      url: /
    - name: Rules
      url: /rules/
    - name: Judges
      url: /judges/
    - name: Sponsors
      url: /sponsors/

sponsors:
    - url: http://dev-extend.eu
      alt_text: Visit Dev:Extend
      img_src: /static/img/devextend.jpg
    - url: http://kodiak.is
      alt_text: Visit Kodiak
      img_src: /static/img/kodiak.png
    - url: http://spawngrid.com
      alt_text: Visit Spawngrid
      img_src: /static/img/spawngrid.png