nav:
  - name: Home
    url: /
  # - name: Rules
  #   url: /rules/
  - name: Sponsors
    url: /#sponsors
  - name: Contact
    url: /#contact

rules:
  - text: TODO
    details:
      - text: Choose <code>XX</code>
      - text: <code>YY = XX + 1</code>
      - text: <code>ZZ = XX - 2</code>
      - text: Add specific prizes if we can
  - text: "Schedule"
    details:
      - text: "The event will start on <strong>2017-12-XX 00:00 UTC</strong>."
      - text: "The event will end on <strong>2017-12-YY 23:59 UTC</strong>."
      - text: "Each team will have exactly 48 hours to work on their projects."
  - text: Teams
    details:
      - text: "Team size is 1 to 4."
      - text: "Every team member has to be a human being, not an organization."
      - text: "All members of the team should be 13 years old or older."
      - text: "Judges of this contest can not participate in it as members of a team."
      - text: "All teams should be registered by <strong>2017-12-ZZ 23:59 UTC</strong>."
  - text: Projects
    details:
      - text: "All projects should be written to run on the Erlang VM / BEAM."
      - text: "They can be written in any BEAM-based language (i.e. Erlang, Elixir, LFE, efene, clojerl, etc.)."
      - text: "Supplementary languages such as Javascript (and JS frameworks) are allowed."
      - text: "No code can be created before the start of the contest."
      - text: "The organizing team will create a git repository at GitHub for each team."
      - text: "If a team needs more than one, they can ask the organizers to create extra repos for them."
      - text: "All deliverables should be uploaded to the repository, which is what will be used by the jury to evaluate the projects."
      - text: "The only required deliverable is the code, but everything in the repository will be used for evaluation."
      - text: "Suggested extra deliverables to include: Documentation, comprehensive README.md, project-related art (e.g. Logos), tests and anything that makes building and understanding the system easier for the judges."
      - text: "Usage of third party libraries and web services is not prohibited, even encouraged."
      - text: "<em>Ownership and Copyright:</em> Each team retains all the rights to their submissions."
      - text: "<em>User Privacy:</em> If a project is an online application (such as a web application) that collects personal information from its users, it should not reveal any of personally identifiable information unless required to do so by law. Please respect people&#8217;s privacy."
      - text: "Lawful submissions only: please do not submit anything that can be considered harmful, unlawful or both."
  - text: Evaluation
    details:
      - text: "Your work will be judged by a publicly know jury, unless previously disqualified."
      - text: "Each sponsor is responsible for delivering the prize they provided to the corresponding winner team."
      - text: "Each project will be evaluated in 6 different categories: Creativity, Usefulness, Innovation, Correctness, Maintainability and Completion."
      - text: "Final score of each team will be computed as the sum of the points received in all those categories."
      - text: "The team with the highest final score will be the winner of the contest."
      - text: "Other prizes, besides the one for the winner, will be awarded as well."
  - text: Other Rules
    details:
      - text: "Individual participants or even entire teams can be disqualified if they don't abide to these rules. The organizers reserve the rights to apply the punishment they consider fit to any transgression."
      - text: "Event organizers will not reimburse you for any expenses or losses."
      - text: "Event organizers are not responsible for any damage, legal actions or any other outcomes that might be a result of your participation."
      - text: "Event organizers reserve the right to change these rules without prior notification."
