nav:
  - name: Registration
    url: /registration
  - name: Rules
    url: /rules
  - name: Judges
    url: /judges
  - name: Sponsors
    url: /sponsors
  - name: Prizes
    url: /prizes
  - name: Contact
    url: /#contact

platinum_sponsor:
  name: PegB
  image: pegb.svg
  logo: pegb_logo.svg
  url: https://www.pegb.tech/
  description: Secure Cashless Payments for everyone, everywhere
  background_color: "#f05323"

gold_sponsors:
  - name: AdRoll
    image: droll.svg
    logo: droll.png
    url: https://www.adroll.com/
    description: The retargeting and prospecting platform of choice for over 35,000 advertisers worldwide
    background_color: "#00aeef"
  - name: Alert Logic
    image: alertlogic.svg
    logo: alertlogic.png
    url: https://www.alertlogic.com/
    description: Security as a Service
    background_color: "#ff7e00"
  - name: BairesDev
    image: bairesdev.svg
    logo: bairesdev.png
    url: https://www.bairesdev.com/
    description: "Leaders in Staff Augmentation: The extra talent needed to boost your projects"
    background_color: "#1774b3"

prizes:
  - name: 600USD ThinkGeek Gift Certificate
    sponsor: BairesDev
    sponsor_url: https://www.bairesdev.com/
    url: https://www.thinkgeek.com/brain/order/certificate.cgi
    image: thinkgeek-gift-card.jpg
  - name: 500USD Gyft Card
    sponsor: Alert Logic
    sponsor_url: https://www.alertlogic.com/
    url: https://www.gyft.com/buy-gift-cards/gyft-card/?category=Featured%20Gift%20Cards
    image: gyft-card.png
  - name: 300USD Amazon Gift Card
    sponsor: AdRoll
    sponsor_url: https://www.adroll.com/
    url: https://www.amazon.com/gift-cards/
    image: amazon-gift-card.png
  - name: 300USD Sparkfun Gift Certificate
    sponsor: AdRoll
    sponsor_url: https://www.adroll.com/
    url: https://www.sparkfun.com/products/13726
    image: sparkfun-gift-certificate.jpg

judges:
  - name: Fred Hebert
    url: https://ferd.ca/
    twitter: mononcqc
    image: fred.jpg
  - name: Joe Armstrong
    url: https://joearms.github.io/
    twitter: joeerl
    image: joe.jpg
  - name: Christopher Meiklejohn
    url: http://christophermeiklejohn.com/
    twitter: cmeik
    image: chris.jpeg
  - name: René Föhring
    url: http://trivelop.de/
    twitter: rrrene
    image: rrrene.png
  - name: Marcelo Gornstein
    url: https://marcelog.github.io/
    twitter: mgornstein
    image: chelo.jpeg

rules:
  - text: "Schedule"
    details:
      - text: The event will start on <strong>2017-12-09 00:00 UTC</strong>.
      - text: The event will end on <strong>2017-12-10 23:59 UTC</strong>.
      - text: The registration will close 2 days prior to the start date.
      - text: Each team will have exactly 48 hours to work on their projects.
  - text: Teams
    details:
      - text: "Team size is 1 to 4."
      - text: "Every team member has to be a human being, not an organization."
      - text: "All members of the team should be 13 years old or older."
      - text: "Judges of this contest can not participate in it as members of a team."
      - text: Every team has to be registered by completing the <a target="_blank" href="https://goo.gl/forms/kCY0ekjqZI6PPZRl2">registration form</a>.
  - text: Projects
    details:
      - text: "All projects should be written to run on the Erlang VM / BEAM."
      - text: "They can be written in any BEAM-based language (i.e. Erlang, Elixir, LFE, efene, clojerl, etc.)."
      - text: "Supplementary languages such as Javascript (and JS frameworks) are allowed."
      - text: "No code can be created before the start of the contest."
      - text: Each team should come up with their own project idea (If you need inspiration check <a target="_blank" href="https://appideagenerator.com/">this website</a>)
      - text: "The organizing team will create a git repository at GitHub for each team."
      - text: "If a team needs more than one, they can ask the organizers to create extra repos for them."
      - text: "All deliverables should be uploaded to the repository, which is what will be used by the jury to evaluate the projects."
      - text: "The only required deliverable is the code, but everything in the repository will be used for evaluation."
      - text: "Suggested extra deliverables to include: Documentation, comprehensive README.md, project-related art (e.g. Logos), tests and anything that makes building and understanding the system easier for the judges."
      - text: "Usage of third party libraries and web services is not prohibited, even encouraged."
      - text: "<em>Ownership and Copyright:</em> Each team retains all the rights to their submissions."
      - text: "<em>User Privacy:</em> If a project is an online application (such as a web application) that collects personal information from its users, it should not reveal any of personally identifiable information unless required to do so by law. Please respect people&#8217;s privacy."
      - text: "Lawful submissions only: please do not submit anything that can be considered harmful, unlawful or both."
  - text: Evaluation
    details:
      - text: "Your work will be judged by a publicly known jury, unless previously disqualified."
      - text: "Each sponsor is responsible for delivering the prize they provided to the corresponding winning team."
      - text: "Each project will be evaluated in 6 different categories: Creativity, Usefulness, Innovation, Correctness, Maintainability and Completion."
      - text: "Final interpretation of each category meaning is up to the judges, but as general guidelines:
              <dl>
                <dt>Creativity</dt><dd>This category assigns points for unexpectedness, eccentricity, fun. This is a broad category that may apply to the project, its code, the team, etc.</dd>
                <dt>Usefulness</dt><dd>How useful the project will be for its target users. Does it solve an existing problem? Does it significantly reduce work time for its users?</dd>
                <dt>Innovation</dt><dd>How groundbreaking the project is. The more unique and unprecedented the idea behind the project, the better. Also applies to projects developed in a unique way.</dd>
                <dt>Correctness</dt><dd>The less bugs, the better. This category values working products over complete ones.</dd>
                <dt>Maintainability</dt><dd>How easy will be for future developers to keep contributing to this project after SpawnFest is over.</dd>
                <dt>Completion</dt><dd>Is the project functional? Did the team get to a point where there is something to show, even if there are a few bugs here and there?</dd>
              </dl>
              "
      - text: "Final score of each team will be computed as the sum of the points received in all those categories."
      - text: "The team with the highest final score will be the winner of the contest."
      - text: "Other prizes, besides the one for the winner, will be awarded as well."
  - text: Other Rules
    details:
      - text: "Individual participants or even entire teams can be disqualified if they don't abide by these rules. The organizers reserve the right to apply the punishment they consider fit to any transgression."
      - text: "Event organizers will not reimburse you for any expenses or losses."
      - text: "Event organizers are not responsible for any damage, legal actions or any other outcomes that might be a result of your participation."
      - text: "Event organizers reserve the right to change these rules without prior notification."
