safe: true
lsi: false
pygments: true

description: "An annual 48 hour development competition in which teams of skilled application developers get exactly one weekend to develop the best Erlang software that they can"

nav:
    - name: Register
      url: /take-part/
    - name: Find a team
      url: /find-a-team/
    - name: Rules
      url: /rules/
    - name: Prizes
      url: /prizes/
    - name: Judges
      url: /judges/

sponsors:
    - url: http://www.soft10.es
      alt_text: Visit Soft10
      img_src: /static/img/soft10.jpg
    - url: http://dev-extend.eu
      alt_text: Visit Dev:Extend
      img_src: /static/img/devextend.jpg
    - url: http://github.com/
      alt_tetx: Visit GitHub
      img_src: /static/img/github.png
    - url: http://erlang-solutions.com
      alt_text: Visit Erlang Solutions
      img_src: /static/img/esl.png
    - url: http://kodiak.is
      alt_text: Visit Kodiak
      img_src: /static/img/kodiak.png
    - url: http://spawngrid.com
      alt_text: Visit Spawngrid
      img_src: /static/img/spawngrid.png
    - url: http://www.manning.com/
      alt_text: Visit Manning
      img_src: /static/img/manning.gif
    - url: http://www.oreilly.com/
      alt_text: Visit O'Reilly
      img_src: /static/img/oreilly.png
    - url: http://inakanetworks.com/
      alt_text: Visit Inaka Networks
      img_src: /static/img/inaka.png
    - url: http://www.gandi.net/
      alt_text: Visit Gandi
      img_src: /static/img/gandi.gif
